on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  schedule:
    - cron: '12 15 * * *'
  workflow_dispatch:
jobs:
  sphinx:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - apple-codesign/docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.10'
      - name: Run Sphinx
        run: |
          python3.10 -m pip install Sphinx==5.1.1
          make -C ${{ matrix.dir }} html
